### ISSUE TITLE
INT_MAX 宏定义与标准库冲突

### ISSUE THREAD

**Issue by FanShupei** [eesast/TeamStyle19-BUG-Report#13]
BUG位置：平台

### 运行环境

* 操作系统版本：
* C/C++编译器版本：
* 使用平台版本：win_03_26_03
* 使用界面版本：

### BUG描述

平台客户端代码中 api_player.h 定义了 `#define INT_MAX 1000000` 但 INT_MAX 本身是标准库 limits.h 的一部分，建议修改

**Comment by wangqr** [comment]
Fixed
