### ISSUE TITLE
[Feature Request]API命名有一些不合理的地方，无法愉快使用std::map。

### ISSUE THREAD

**Issue by HuangMT** [eesast/TeamStyle19-BUG-Report#14]
BUG位置：平台

### 运行环境

* 操作系统版本：win8.1
* C/C++编译器版本：VS2017
* 使用平台版本：0330
* 使用界面版本：x

### BUG描述
官方头文件里有using namespace std; 并且官方的地图变量又叫int** map；这就会无法用常规方法使用std::map，希望把using namespace放到.cpp里，或者把map这个名字给改了，感激不尽
（在这里描述BUG出现的情况，例如进行某一接口调用时未达到期望效果，在某一事件出现时系统崩溃等）

**Comment by wangqr** [comment]
Fixed in next release
