### ISSUE TITLE
[Feature Request]API设计有一丝不合理，无法愉快使用std::map。

### ISSUE THREAD

**Issue by HuangMT** [eesast/TeamStyle19-BUG-Report#15]
BUG位置：平台

### 运行环境

* 操作系统版本：win8.1
* C/C++编译器版本：VS2017
* 使用平台版本：0330
* 使用界面版本：0000

### BUG描述
官方头文件中有using namespace std; 而官方存地图的变量叫做map；于是就无法用常规的方法使用std::map了，希望把using namespace删掉或者把地图的名字改成别的什么。

**Comment by wangqr** [comment]
Duplicate of #14
