### ISSUE TITLE
b组网站崩溃，连接清华网后其他网页(a1组能访问)都能访问，就是b组网址无法响应

### ISSUE THREAD

**Issue by silentsaber** [eesast/TeamStyle19-BUG-Report#16]
BUG位置：（平台/网站/界面/逻辑/其他/不确定）

### 运行环境

* 操作系统版本：
* C/C++编译器版本：
* 使用平台版本：
* 使用界面版本：

### BUG描述

（在这里描述BUG出现的情况，例如进行某一接口调用时未达到期望效果，在某一事件出现时系统崩溃等）

**Comment by wangqr** [comment]
您好，这里为A1组bug反馈用，我们会转达上述问题
