### ISSUE TITLE
[BUG]state->building[flag]使用错误

### ISSUE THREAD

**Issue by rcy17** [eesast/TeamStyle19-BUG-Report#2]
BUG位置：逻辑
运行环境：windows
操作系统版本：10.0.15063
C/C++编译器版本：VS2012
使用平台版本：playerfile0312
使用界面版本：NULL
BUG描述：state->building[flag].size()取值错误，具体来说建筑第一个建筑前为0，之后恒为1，猜测是STL相关操作问题

**Comment by snowareas** [comment]
此问题已修复

**Comment by WangMinhu** [comment]
BUG Report Grade: 3
