### ISSUE TITLE
[BUG]建筑消耗资源数有误

### ISSUE THREAD

**Issue by rcy17** [eesast/TeamStyle19-BUG-Report#3]
BUG位置：逻辑
运行环境：windows
操作系统版本：10.0.15063
C/C++编译器版本：VS2012
使用平台版本：playerfile0312
使用界面版本：NULL
BUG描述：后台已知时代错误，这里不再累赘。但是就读取结果而言，时代被锁定为3，此时根据规则所有建筑物造价格应该为基础造价的2倍（或者1.5倍？某些地方定义给的不是很清楚）。但事实上，建造一个基础资源为100的香农消耗资源为500，哪里不太对？

**Comment by snowareas** [comment]
时代值为3表示第四个时代，按照规则应该消耗资源250点，可以看看是不是造了两个建筑，所以消耗500点？

**Comment by snowareas** [comment]
刚刚去调了一下，应该是选手这边传回来的建筑信息不全，只保留了一个

**Comment by snowareas** [comment]
今晚将发布新版本解决该问题

**Comment by WangMinhu** [comment]
BUG Report Grade: 3
