### ISSUE TITLE
[Enhancement]请优化平台打包

### ISSUE THREAD

**Issue by FanShupei** [eesast/TeamStyle19-BUG-Report#5]
BUG位置：平台

### 运行环境

* 操作系统版本：Windows 10
* C/C++编译器版本：
* 使用平台版本：0311_02
* 使用界面版本：

### BUG描述

文件体积巨大，使用不便，且每运行一次会在Temp文件夹下写入约500M文件（其中有400M临时文件是MKL），请优化。

**Comment by wangqr** [comment]
removed dependency `pillow`, which depends on `PyQt`, `tkinter`, etc.
