### ISSUE TITLE
[QUESTION]如何处理计算超时行为

### ISSUE THREAD

**Issue by FanShupei** [eesast/TeamStyle19-BUG-Report#6]
目前尚处于内测阶段，拿不到详细说明，故请求开发组说明。

如果选手在回合中计算超时，平台如何处理
* 直接判负？
* 予以分数惩罚，但等待程序计算完成。如果超时过长再判负？
* 认为选手未发出任何指令，直接进入下一环节？

如果选手计算超时，接下来能否保证 `recv_state()` 拿到的永远是最新的 `State` ？

如果选手计算超时，而平台决定进入下一回合。此时选手再传回的指令可能为非法指令，平台如何处理？

**Comment by JulySinceAndrew** [comment]
已经在最新的接口文档中给出了说明
