### ISSUE TITLE
[BUG]mac版本编译出错

### ISSUE THREAD

**Issue by Gaffey** [eesast/TeamStyle19-BUG-Report#7]
BUG位置：平台

### 运行环境

* 操作系统版本：OS X 10.12.6
* C/C++编译器版本：4.2.1
* 使用平台版本：playerfile_mac_0313_01
* 使用界面版本：None

### BUG描述

communication.cpp文件中第209行和第213行的level未定义导致编译出错，猜测应该是levels

**Comment by duzx16** [comment]
代码已经在仓库修改，会随着下一个版本的平台发布而修复

**Comment by WangMinhu** [comment]
BUG Report Grade:3
